name: Murmurs
options:
  useBaseInternationalization: false
  enableBaseInternationalization: false
  groupOrdering:
    - order: [Sources, Resources, Shared]
settings:
  MARKETING_VERSION: 0.3.5
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: TBPGXSQHVE
  CURRENT_PROJECT_VERSION: 1
  VERSIONING_SYSTEM: apple-generic
packages:
  XLog:
    path: ./Packages/XLog
  XLang:
    path: ./Packages/XLang
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.0
  ConfettiSwiftUI:
    url: https://github.com/simibac/ConfettiSwiftUI.git
    from: 1.1.0
  DSWaveformImage:
    url: https://github.com/dmrschmidt/DSWaveformImage
    from: 13.0.2
  CSV:
    url: https://github.com/yaslab/CSV.swift.git
    from: 2.4.3
  TPPDF:
    url: https://github.com/techprimate/TPPDF.git
    from: 2.4.1
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.4.0
configs:
  Debug: debug
  Snapshot: debug
  AppStore: release
schemes:
  Murmurs:
    build:
      targets:
        Murmurs: all
      config: Debug
    test:
      targets:
        - name: MurmursTests
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": true
        "-com.apple.CoreData.SQLDebug 1": true
  MurmursWatch:
    build:
      targets:
        MurmursWatch: all
      config: Debug
    run:
      config: Debug
  SnapshotTests:
    build:
      targets:
        SnapshotTests: test
    test:
      targets:
        - SnapshotTests
      config: Snapshot
targets:
  MurmursWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    dependencies:
      - package: XLog
      - package: XLang
      - target: MurmursWatchWidget
    sources:
      - Watch
      - Shared
    info:
      path: Watch/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        WKCompanionAppBundleIdentifier: com.tangyue.murmurs
        NSMicrophoneUsageDescription: "Murmurs requires access to your microphone."
        UIBackgroundModes: [audio]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tangyue.murmurs.watch
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
  MurmursWatchWidget:
    type: app-extension
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - WatchWidget
    info:
      path: WatchWidget/Info.plist
      properties:
        CFBundleDisplayName: Murmurs
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tangyue.murmurs.watch.widget
        GENERATE_INFOPLIST_FILE: true
  MurmursTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    path: Tests/Info.plist
    sources:
      - Tests
    dependencies:
      - target: Murmurs
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.tangyue.murmurs.tests
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_MACCATALYST: NO
  MurmursWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - package: XLog
    sources:
      - WatchWidget
      - Shared/LiveActivity
      - path: Shared/NotificationNames.swift
    info:
      path: WatchWidget/Info.plist
      properties:
        CFBundleDisplayName: Murmurs
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tangyue.murmurs.widget
        GENERATE_INFOPLIST_FILE: true
        SKIP_INSTALL: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: TBPGXSQHVE
  Murmurs:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    entitlements:
      path: Resources/Murmurs.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.tangyue.murmurs
        com.apple.developer.icloud-services:
          - CloudDocuments
          - CloudKit
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.tangyue.murmurs
    dependencies:
      - package: XLog
      - package: XLang
      - package: KeychainAccess
      - package: ConfettiSwiftUI
      - package: CSV
      - package: TPPDF
      - package: DSWaveformImage
        product: DSWaveformImage
      - package: DSWaveformImage
        product: DSWaveformImageViews
      - package: MarkdownUI
      - target: MurmursWatch
      - target: MurmursWidget
    sources:
      - Sources
      - Resources
      - Shared
    info:
      path: Resources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        GIT_HASH: "${GIT_HASH}"
        UILaunchStoryboardName: Launch Screen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
        ITSAppUsesNonExemptEncryption: false
        NSSpeechRecognitionUsageDescription: "Access to speech recognition functionality is required."
        NSMicrophoneUsageDescription: "Murmurs requires access to your microphone so that you can record entries in your journal."
        NSSupportsLiveActivities: true
        UIBackgroundModes: [audio]
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.tangyue.murmurs
            CFBundleURLSchemes:
              - murmurs
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1,2
        PRODUCT_BUNDLE_IDENTIFIER: com.tangyue.murmurs
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      configs:
        Snapshot:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: [DEBUG, SNAPSHOT]
  SnapshotTests:
    type: bundle.ui-testing
    deploymentTarget: "17.0"
    platform: iOS
    sources: [SnapshotTests]
    dependencies:
      - target: Murmurs
    settings:
      INFOPLIST_FILE: Resources/Info.plist
