name: Run Unit Tests
on: 
  push:
    branches:
      - release/*
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          bundle install
          brew install xcodegen
          xcodegen
          bundle exec fastlane tests